### ISSUE TITLE
RFID keyboard inserts unnecessary 0s into output

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/doorbot-setup#15]
Trying out the RFID keyboard mentioned in https://github.com/DoESLiverpool/doorbot-setup/issues/11#issuecomment-142584710 just now with @paulfurley's card, it ended up adding an extra 0 to the octet that was less than 0x10.

I'd have raised the issue on the keyboard's repo directly, but can't remember my login details for it.

**Comment by DefProc** [comment]
Ah, most likely lines 81–85 in `arduino/src/sketch.ino`. I'll get on it.

**Comment by DefProc** [comment]
Fixed
