### ISSUE TITLE
Add a power switch to the custom PCB

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/doorbot-setup#16]
We should add a reset button or power switch to the custom PCB to make it easier to power-cycle a non-responding doorbot (rather than having to pull the lead out of the PC power supply, as is the current option with doorbot1)

**Comment by amcewen** [comment]
The newer Pi boards have a two-pin "RUN" connector, which can be used for a reset button.  It's not easy to pull onto the custom PCB, and it'd make more sense to wire it to a panel-mount button rather than one on the PCB (e.g. as suggested in https://github.com/DoESLiverpool/somebody-should/issues/451) so closing this as "won't fix".

**Comment by DefProc** [comment]
The [UPS Pico](https://www.modmypi.com/raspberry-pi/breakout-boards-229/pi-modules/ups-pico) uses an (optional) pogo pin from the HAT to this hole location as a reset monitor. It's close enough to the 40-pin header that the connection has been reliable in my use.
