### ISSUE TITLE
Add space for an I2S DAC for audio on the PCB

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/doorbot-setup#17]
We could add one of [these I2S DAC boards with on-board amplifier](https://shop.pimoroni.com/products/adafruit-i2s-3w-class-d-amplifier-breakout-max98357a) to the doorbots in order to get better audio output (or remove the requirement for separate PC speakers)

See [my museuminabox work](https://github.com/museuminabox/brain/tree/master/Physical) for details of how to wire up the board (and check out the Ansible scripts elsewhere in that repo for details of how to configure the software side of the audio)

**Comment by jamieisboss** [comment]
You dont really need the I2S i think unless you want some feature, you could just get some of the [very cheap (5V) PAM8403 boards](http://www.ebay.co.uk/itm/PAM8403-module-mini-digital-amplifier-board-2-3W-Class-D-amplifier-E69-/221435118465?roken=cUgayN) which will drive 2x 3w speakers, or build the PAM8403 into the pcb.

if you dont have an audio out you can use the [PWM DTO](https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README#L1056) to get audio over the gpio and then amplify it
