### ISSUE TITLE
Ringtones aren't copied

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/doorbot-setup#2]
Need to decide how to deal with ringtones. They either need to be stored in the bitbucket repository with the rest of the config, or once the doorbot has been setup a script needs to be run to copy them from doorbot1 to the other machines. Former probably better so that they're stored and backed up somewhere properly.

**Comment by DefProc** [comment]
Agreed that the settings repo is the ideal place as it includes the config file that relates to them.

**Comment by DefProc** [comment]
Ringtones are now in the doorbots config directory, from [#bb5d2486](https://gitlab.com/DoESLiverpool/doorbots-config/commit/bb5d24869f60d6f248e59d2692ec997d684cfa74) (organiser gitlab login required)

**Comment by ajlennon** [comment]
Is there any way I can modify my own ring tone? Rick is beginning to grate (well tbh he began to grate a while ago...)

**Comment by DefProc** [comment]
@ajlennon Currently the process is either "become a full organiser" or "email an organiser and ask for a change".

We can't really give public access to the attendee list and access permissions :warning:→:skull:→:hamburger:, so an extra authorisation step is necessary atm.

**Comment by ajlennon** [comment]
Rightho. I'll fine a replacement and send an email :)
