### ISSUE TITLE
Better mounting for Doorbot2 (kitchen/workshop)

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/doorbot-setup#5]
If left to wobble around in its current cardboard box enclosure, Doorbot2 is prone to rebooting whenever there's a knock to the door, like when the door shuts :-)

We should find a proper mounting solution for the Pi and the little breakout board, so they can't move around.

**Comment by johnmckerrell** [comment]
Closing this as we're no longer in Gostins!
