### ISSUE TITLE
Init script documentation/repo/deployed don't match

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/doorbot-setup#7]
The readme.md lists "Copy the startup script into /etc/init" in the "To be done" section.  

The remote-setup.rb script includes the line:
    ssh.exec!("sudo cp /home/pi/logcards/init/logcards /etc/init.d/") do |channel, stream, data|
which looks like it's copying the script across.

However, none of the doorbots up and running have the logcards script in /etc/init.d

It looks like that's been deprecated, and some script called startup-rfid.sh - which doesn't seem to be checked in anywhere? - is in use instead?

**Comment by johnmckerrell** [comment]
It's quite possible that none of the live doorbots are built from the setup script, if any it will just be doorbot3 but I don't think that one is, so this would be a new rather than old step.

**Comment by amcewen** [comment]
The README and code now match, and I've run through it on the new Doorbot1.  I guess we can leave Doorbot2 (and 3) for now, and see how reliable Doorbot1 is, but it would be good to update them in the medium-term.
