### ISSUE TITLE
No bitbucket credentials on the wiki

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/doorbot-setup#8]
I can't find any way to add my bitbucket user (amcewen) to the DoES repository, so can't clone the config repository.

**Comment by johnmckerrell** [comment]
Added you as an admin. 

--

**Comment by DefProc** [comment]
And me too please (DefProc)

is this the de-facto place to sign-up to get access now then?

**Comment by johnmckerrell** [comment]
It works ;-) Now added, we only get 5 users on the free plan, we're now at 3.

**Comment by DefProc** [comment]
Is the update process documented anywhere?

What happens about new ringtones now?

**Comment by amcewen** [comment]
See issues #2 and #11, and https://github.com/DoESLiverpool/somebody-should/issues/166 :-)

But basically, no.  My current process is:
 * ssh into doorbot1
 * tail logcards/scans.log
 * Add the new person to config.yaml **on my local machine, not the doorbot** and push that to bitbucket
 * On the doorbot, git pull to get the new config
 * Run reload-all-config to copy it across to doorbots 2 and 3

**Comment by DefProc** [comment]
I've

**Comment by DefProc** [comment]
I've made an rfid-keyboard to allow easier collection of the RFID UIDs: https://git.defproc.co.uk/DefProc/rfid-keyboard

So now, with the device plugged in as a USB keyboard, the process to add/search though a local clone of doorbot-setup can be done without ssh'ing to a doorbot for an ID number. 

With the rfid-keyboard plugged in (and having set the keyboard map to QWERTY!): 

 * Add the new person to config.yaml **on your local repo, not the doorbot** (scan the card where you need to input the UID)
 * commit & push that to bitbucket
 * On the doorbot, `cd logcards/doorbot-setup && git pull` to get the new config
 * Run `~/reload-all-config.sh` to copy it across to doorbots 2 and 3
